import assert from 'node:assert/strict'
import test from 'node:test'
import { mkdir } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { builtUiFixture } from './ui-built-fixture.mjs'

// This gate owns a fresh headless browser and real built Host/API/UI; it never uses user browser state.
process.env.PLAYWRIGHT_BROWSERS_PATH ??= fileURLToPath(new URL('../.tmp/playwright-browsers/', import.meta.url))
const { chromium } = await import('playwright')
const output = fileURLToPath(new URL('../.tmp/step14-browser/', import.meta.url))
await mkdir(output, { recursive: true })
test('Chromium operates exact human answers, tasks, messages, fixed events and accepted workflow output', { timeout: 120000 }, async () => {
  const fixture = await builtUiFixture({ question: true, workflow: true })
  let browser, context, page
  try {
    browser = await chromium.launch({ headless: true,
      ...(process.env.ATOMIC_HARNESS_BROWSER_CHANNEL === undefined ? {} : { channel: process.env.ATOMIC_HARNESS_BROWSER_CHANNEL }) })
    context = await browser.newContext({ viewport: { width: 1440, height: 1100 } })
    await context.tracing.start({ screenshots: true, snapshots: true, sources: false })
    page = await context.newPage(); const errors = []
    page.setDefaultTimeout(15000); page.on('pageerror', error => errors.push(error.message))
    const ready = async () => { await page.waitForFunction(() => document.getElementById('busy-label').textContent === '') }
    const queryRoot = async () => { await page.locator('#root-form').getByRole('button', { name: '查询', exact: true }).click(); await ready() }
    await page.goto(fixture.ui.ready.url)
    await page.getByLabel('操作者口令').fill(fixture.password)
    await page.getByRole('button', { name: '登录', exact: true }).click()
    await page.locator('#workspace').waitFor({ state: 'visible' }); await ready()
    await page.locator('#root-select').selectOption({ index: 1 }); await queryRoot()
    assert.match(await page.locator('#root-result').innerText(), /请确认研究结果应使用 Markdown 格式/)
    const answer = page.locator('#root-result form')
    await answer.getByLabel('回答提交键').fill('browser-exact-answer')
    await answer.getByLabel('回答', { exact: true }).fill('Markdown')
    await answer.getByRole('button').click(); await ready()
    assert.match(await page.locator('#operation-result').innerText(), /input.answer/)
    await page.locator('#run').click(); await ready(); await queryRoot()
    assert.match(await page.locator('#root-result').innerText(), /completed/)
    const task = page.locator('#task-form')
    await task.getByLabel('提交键', { exact: true }).fill('browser-task')
    await task.getByLabel('任务', { exact: true }).fill('<script id="injected">throw new Error("injected")</script> research task')
    await task.getByRole('button').click(); await ready()
    await task.getByRole('button').click(); await ready()
    assert.match(await page.locator('#input-result').innerText(), /复用/)
    await page.locator('#run').click(); await ready()
    await page.locator('#input-form').getByRole('button').click(); await ready(); await queryRoot()
    assert.match(await page.locator('#root-result').innerText(), /completed/)
    const rootField = page.locator('#root-form input[name="rootId"]'), currentRoot = await rootField.inputValue()
    assert.equal(await page.locator('#root-select').inputValue(), currentRoot)
    await rootField.fill('ah-event:70000000-0000-4000-8000-000000000101:999999')
    assert.equal(await page.locator('#root-select').inputValue(), '')
    await rootField.fill(currentRoot)
    await page.getByRole('button', { name: '刷新状态', exact: true }).click(); await ready()
    assert.equal(await page.locator('#root-select').inputValue(), currentRoot)
    await queryRoot()
    assert.equal(await page.locator('#injected').count(), 0)
    await page.screenshot({ path: `${output}/tasks.png`, fullPage: true })
    await page.getByRole('button', { name: 'Session 通信', exact: true }).click()
    const message = page.locator('#message-form')
    await message.getByLabel('Peer 键（发送）').fill('reviewer')
    await message.getByLabel('JSON 载荷').fill('{"text":"browser research evidence"}')
    await message.getByRole('button').click(); await ready()
    await page.locator('#message-result summary').click()
    assert.match(await page.locator('#message-result').innerText(), /outbox-accepted/)
    await page.locator('#run').click(); await ready()
    await page.locator('#message-query-form').getByRole('button', { name: '查询', exact: true }).click(); await ready()
    await page.locator('#message-result summary').click()
    assert.match(await page.locator('#message-result').innerText(), /messageId/)
    await page.getByRole('button', { name: '事件历史', exact: true }).click()
    await page.locator('#events-form input[name="maxEvents"]').fill('2')
    await page.locator('#events-form').getByRole('button').click(); await ready()
    const first = await page.locator('#events-result').innerText(), through = first.match(/through=(\d+)/)[1]
    await page.locator('#events-next').click(); await ready()
    assert.match(await page.locator('#events-result').innerText(), new RegExp(`through=${through} ·`))
    await page.screenshot({ path: `${output}/events.png`, fullPage: true })
    await page.getByRole('button', { name: 'Workflow', exact: true }).click()
    const workflow = page.locator('#workflow-form')
    await workflow.getByLabel('控制请求键').fill('browser-workflow-resume')
    await workflow.getByRole('button', { name: '恢复 Workflow', exact: true }).click(); await ready()
    await page.locator('#run').click(); await ready()
    await workflow.getByRole('button', { name: '查询', exact: true }).click(); await ready()
    assert.match(await page.locator('#workflow-result').innerText(), /资源与协议关闭：是/, await page.locator('#notice').textContent())
    await page.locator('#workflow-result').getByRole('button', { name: /^读取产物 / }).first().click(); await ready()
    assert.match(await page.locator('#artifact-result').innerText(), /writer answer/)
    await page.screenshot({ path: `${output}/workflow.png`, fullPage: true })
    assert.deepEqual(errors, [])
    await page.getByRole('button', { name: '退出', exact: true }).click()
    await page.locator('#login-view').waitFor({ state: 'visible' })
    assert.equal(fixture.service.status, 'ready')
  } finally {
    if (page !== undefined) await page.screenshot({ path: `${output}/last.png`, fullPage: true })
    if (context !== undefined) await context.tracing.stop({ path: `${output}/trace.zip` })
    await browser?.close(); await fixture.dispose()
  }
})
