/** Versioned delegation facts and public configuration; execution authority is issued only by a Host. */
export type { DelegationRequest, DelegationWorkspace, DelegationCapabilities, DelegationRequirements, AgentSubagentRole, SubagentLimits } from './contract.js'
export type { ChildTemplate, ChildToolConfig } from './template.js'
export type { DelegationReceipt } from './admission.js'
export type { SubagentState } from './state.js'
export type { SubagentFile, SubagentUncertainFile, SubagentMessagePayloads } from './messages.js'
export { decodeChildTemplate } from './template.js'
export { decodeDelegationRequest, decodeSubagentLimits } from './request.js'
export { subagentMessageDefinitions, subagentMessageKinds, decodeSubagentMessage } from './messages.js'
export { SubagentError, subagentErrorCodes } from './errors.js'
export type { SubagentErrorCode } from './errors.js'
export { delegationClosure } from './closure.js'
export type { DelegationClosure } from './closure.js'
export * from './session-events.js'
